### ISSUE TITLE
Yarn add -D @mswjs/source is failing

### ISSUE THREAD

**Issue by Houtheyfa** [mswjs/source#64]
## Description
I am trying to install `msw` and `@mswjs/source` on monorepo package based on Yarn Workspace using Yarn 4.5.1. 
The install is failing due to `@mswjs/source` peer dependencies to `@faker-js`.  I tried running the command on Powershell with admin privileges but i got the same error.  

Below is the terminal output: 

```bash
$ yarn add -D msw @mswjs/source
➤ YN0000: · Yarn 4.5.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @mswjs/source@npm:0.3.1, @faker-js/faker@npm:8.4.1, @stoplight/json@npm:3.21.7, and 13 more.
➤ YN0000: └ Completed in 1s 218ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0001: │ Error: @faker-js/faker@npm:8.4.1: UNKNOWN: unknown error, open 'C:\Users\USER~1\AppData\Local\Temp\xfs-96944d2d\archive.zip'      
    at Object.openSync (node:fs:573:18)
    at Object.writeFileSync (node:fs:2359:35)
    at _n.writeFileSync (C:\Users\USER\AppData\Local\node\corepack\v1\yarn\4.5.1\yarn.js:9:11770)
    at Zi.saveAndClose (C:\Users\USER\AppData\Local\node\corepack\v1\yarn\4.5.1\yarn.js:149:197004)
    at D (C:\Users\USER\AppData\Local\node\corepack\v1\yarn\4.5.1\yarn.js:199:1616)
    at async x (C:\Users\USER\AppData\Local\node\corepack\v1\yarn\4.5.1\yarn.js:199:1916)
    at async C (C:\Users\USER\AppData\Local\node\corepack\v1\yarn\4.5.1\yarn.js:199:3253)
    at async t.fetchPackageFromCache (C:\Users\USER\AppData\Local\node\corepack\v1\yarn\4.5.1\yarn.js:199:3374)
    at async t.fetch (C:\Users\USER\AppData\Local\node\corepack\v1\yarn\4.5.1\yarn.js:688:2451)
    at async py.fetch (C:\Users\USER\AppData\Local\node\corepack\v1\yarn\4.5.1\yarn.js:141:463)
➤ YN0000: └ Completed in 31s 283ms                                                                                                              
➤ YN0000: · Failed with errors in 32s 526ms
```

**Comment by kettanaito** [comment]
Hi, @Houtheyfa. This doesn't look like it's related to Source. Please raise this in the Yarn repo, the team there should provide you with suggestions. Thanks.
